In [1]:
# Para este notebook, é necessária a instalação dos seguintes pacotes
# Transformers (pip install)
# Tensorflow (pip install)
# Pytorch (conda)
from transformers import pipeline
import tensorflow
import torch

import nltk
from nltk.corpus import stopwords
import spacy
import gensim

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from PIL import Image

import warnings
warnings.filterwarnings('ignore')

In [2]:
path = "C:\\Temp\\GoogleNews-vectors-negative300.bin"
w2v_model = gensim.models.KeyedVectors.load_word2vec_format(path, binary=True)

In [3]:
w2v_vet = w2v_model['happy']
w2v_vet

array([-5.18798828e-04,  1.60156250e-01,  1.60980225e-03,  2.53906250e-02,
        9.91210938e-02, -8.59375000e-02,  3.24218750e-01, -2.17285156e-02,
        1.34765625e-01,  1.10351562e-01, -1.04980469e-01, -2.90527344e-02,
       -2.38037109e-02, -4.02832031e-02, -3.68652344e-02,  2.32421875e-01,
        3.20312500e-01,  1.01074219e-01,  5.83496094e-02, -2.91824341e-04,
       -3.29589844e-02,  2.11914062e-01,  4.32128906e-02, -8.59375000e-02,
        2.81250000e-01, -1.78222656e-02,  3.79943848e-03, -1.71875000e-01,
        2.06054688e-01, -1.85546875e-01,  3.73535156e-02, -1.21459961e-02,
        2.04101562e-01, -3.80859375e-02,  3.61328125e-02, -8.15429688e-02,
        8.44726562e-02,  9.37500000e-02,  1.44531250e-01,  7.42187500e-02,
        2.51953125e-01, -7.91015625e-02,  8.69140625e-02,  1.58691406e-02,
        1.09375000e-01, -2.23632812e-01, -5.15747070e-03,  1.68945312e-01,
       -1.36718750e-01, -2.51464844e-02, -3.85742188e-02, -1.33056641e-02,
        1.38671875e-01,  

In [4]:
print(len(w2v_vet))

300


In [5]:
# import gensim.downloader as api
# model = api.load('glove-twitter-25')

path = "C:\\Temp\\glove.twitter.27B.25d.txt"
glv_model = gensim.models.KeyedVectors.load_word2vec_format(path)

In [6]:
glv_vet = glv_model['happy']
glv_vet

array([-1.2304 ,  0.48312,  0.14102, -0.0295 , -0.65253, -0.18554,
        2.1033 ,  1.7516 , -1.3001 , -0.32113, -0.84774,  0.41995,
       -3.8823 ,  0.19638, -0.72865, -0.85273,  0.23174, -1.0763 ,
       -0.83023,  0.10815, -0.51015,  0.27691, -1.1895 ,  0.98094,
       -0.13955], dtype=float32)

In [7]:
path = "C:\\Temp\\wiki-news-300d-1M.vec"
fst_model = gensim.models.KeyedVectors.load_word2vec_format(path, limit=999999)

In [8]:
fst_vet = fst_model['happy']
fst_vet

array([-1.289e-01, -8.410e-02, -1.225e-01, -2.491e-01,  1.207e-01,
        9.570e-02, -7.400e-03,  8.190e-02, -1.289e-01, -1.231e-01,
       -6.860e-02,  2.380e-01,  3.480e-02, -1.954e-01, -6.550e-02,
       -6.660e-02, -2.270e-02, -5.680e-02,  1.426e-01, -1.239e-01,
       -7.200e-02,  1.160e-02,  4.330e-02, -6.540e-02, -1.160e-01,
       -4.990e-02,  4.430e-02, -1.645e-01,  1.130e-02, -6.660e-02,
        3.820e-02,  3.900e-03,  1.792e-01, -5.600e-02,  2.910e-02,
       -1.401e-01,  7.040e-02,  2.550e-02, -3.670e-02,  4.520e-02,
        6.500e-02, -2.950e-02,  4.000e-04, -9.200e-03, -5.360e-02,
       -5.430e-02,  4.190e-02, -8.880e-02, -8.210e-02, -7.070e-02,
       -3.010e-02, -1.271e-01, -7.837e-01, -4.720e-02, -1.050e-01,
       -7.580e-02, -6.430e-02,  9.420e-02, -1.235e-01,  1.001e-01,
       -2.000e-04, -6.500e-03, -7.800e-02, -3.460e-02, -1.522e-01,
       -1.121e-01,  3.380e-02, -6.600e-02, -8.720e-02,  2.050e-02,
       -1.422e-01,  4.150e-02,  6.480e-02,  3.529e-01,  6.100e

## Transformers

In [9]:
# Question-Answering

sentence = r"""Brazil was officially discovered in 1500, when a fleet commanded by Portuguese diplomat Pedro Álvares Cabral, \
on its way to India, landed in Porto Seguro, between Salvador and Rio de Janeiro. There is, however, strong evidence that \
other Portuguese adventurers preceded him. Duarte Pacheco Pereira, in his book De Situ Orbis, tells of being in Brazil \
in 1498, sent by King Manuel of Portugal."""

In [10]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Who discovered Brazil?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Pedro Álvares Cabral,


In [11]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="When Brazil was discovered?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: 1500


In [12]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="How Brazil was discovered?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: a fleet commanded by Portuguese diplomat Pedro Álvares Cabral,


In [13]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Where Brazil was discovered?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Porto Seguro, between Salvador and Rio de Janeiro.


In [14]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Who was the first person in Brazil?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Pedro Álvares Cabral,


In [15]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Who sent Duarte Pacheco Pereira?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: King Manuel of Portugal.


In [16]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Are there any other evidences?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: strong evidence that \
other Portuguese adventurers preceded him.


In [17]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Are there any possibilities that other person was in Brazil before him?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: strong evidence that \
other Portuguese adventurers preceded him.


In [18]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="What is De Situ Orbis?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Duarte Pacheco Pereira, in his book


In [19]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="To where the fleet commanded by Cabral was going?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: India


In [20]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="This guy, Manuel, who was him?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: King Manuel of Portugal.


In [21]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Who was the second person in Brazil?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Duarte Pacheco Pereira,


In [22]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="Who was the third person in Brazil?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: Duarte Pacheco Pereira,


In [23]:
output = pipeline("question-answering", model="csarron/roberta-base-squad-v1")
question = output(question="How was the weather in Brazil?", context=sentence)
print(f"Answer: {question['answer']}")

Answer: \



In [24]:
# Sumarização

nlp = pipeline(task='summarization', model="sshleifer/distilbart-cnn-12-6")
nlp(sentence, max_length=90, min_length=20)

[{'summary_text': ' Brazil was officially discovered in 1500, when a Portuguese diplomat landed in Porto Seguro . Duarte Pacheco Pereira, in his book De Situ Orbis, tells of being in Brazil in 1498 .'}]

In [25]:
# Tradução

nlp = pipeline(task='translation_en_to_fr', model="t5-base")
print(f"{nlp(sentence)[0]['translation_text']}")

Le Brésil a été officiellement découvert en 1500, lorsqu'une flotte commandée par le diplomate portugais Pedro lvares Cabral,  en route vers l'Inde, a débarqué à Porto Seguro, entre Salvador et Rio de Janeiro. Il existe toutefois de solides preuves que  d'autres aventuriers portugais l'ont précédé. Duarte Pacheco Pereira


In [26]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
  
tokenizer = AutoTokenizer.from_pretrained("unicamp-dl/translation-en-pt-t5")
model = AutoModelForSeq2SeqLM.from_pretrained("unicamp-dl/translation-en-pt-t5")

nlp = spacy.load("en_core_web_sm")
doc = nlp(sentence)
sentence_spans = list(doc.sents)

nlp = pipeline('text2text-generation', model=model, tokenizer=tokenizer)

for i in range(len(sentence_spans)):
    print(nlp(str(sentence_spans[i])))

[{'generated_text': 'O Brasil foi descoberto oficialmente em 1500, quando uma frota comandada pelo diplomata português Pedro Álvares Cabral,'}]
[{'generated_text': 'Há, contudo, fortes evidências de que \\ outros aventureiros portugueses o precederam.'}]
[{'generated_text': 'Em seu livro De Situ Orbis, conta de estar no Brasil \\ \\'}]
[{'generated_text': 'Em 1498, enviados pelo rei Manuel de Portugal.'}]


In [27]:
# Geração automática de texto
nlp = pipeline(task='text-generation', model='gpt2')
nlp("Love is", num_return_sequences=2, max_length = 10000, num_beams = 5, no_repeat_ngram_size  = 2, early_stopping = True)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "Love is a great way to start your day.\n\n4. Don't be afraid to ask for help. You don't have to be a lawyer to get help, but you do need to know what you're getting into. If you've never been to a doctor before, you should be able to tell them about your condition. Ask your doctor if they know how to treat you, and if so, how long it will take for you to go through with it. It's also a good idea to talk to your health care provider before you go to the doctor, so they can figure out what's wrong and what can be done to help you get back on your feet. Your doctor may also want to see if you have any family members who might be at risk of getting sick. Even if it's not a serious medical condition, it may not be enough to stop you from going to an emergency room, or even to take your own life.\n\n\n5. Make sure you are doing everything you can to keep yourself healthy. When it comes to eating, exercise, sleeping, exercising, eating well, working out, being active, get

In [28]:
nlp = pipeline(task='text-generation', model='gpt2')
nlp("Hate is", num_return_sequences=2, max_length = 10000, num_beams = 5, no_repeat_ngram_size  = 2, early_stopping = True)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "Hate is not going to go away.\n\nI'm not saying it's going away, but I'm saying that we need to find a way to get rid of hate speech. It's not something that's been going on for a long time. And we have to do something about it. We have a lot of work ahead of us, and we've got to figure out how to make sure that it doesn't happen again."},
 {'generated_text': 'Hate is the most common form of hate speech in the U.S., according to the Anti-Defamation League (ADL). The ADL estimates that more than one-third of all hate crimes against Jews are committed by non-Jews.\n\nIn an interview with Fox News Channel\'s Greta Van Susteren last year, former President George W. Bush said, "I don\'t think there\'s a single Jew in this country who is going to say that I\'m not a racist or a bigot. I think they\'re all good people, and they\'ve got to be treated with respect and dignity." He added: "There\'s no reason why I can\'t be a good person."'}]

In [29]:
# Classificação de texto
sentence = "I love it!"
nlp = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { nlp(sentence) }")

Result: [{'label': '5 stars', 'score': 0.9018256068229675}]


In [30]:
sentence = "I hate it!"
nlp = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { nlp(sentence) }")

Result: [{'label': '1 star', 'score': 0.8533276319503784}]


In [31]:
sentence = "I thought it would be useful, but it's not worthy."
nlp = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { nlp(sentence) }")

Result: [{'label': '2 stars', 'score': 0.5419707894325256}]


In [32]:
sentence = "My daughter is using it a lot for school."
nlp = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { nlp(sentence) }")

Result: [{'label': '4 stars', 'score': 0.4631804823875427}]


In [33]:
sentence = "It seems that we will have to wait and see."
nlp = pipeline(task="text-classification", model='nlptown/bert-base-multilingual-uncased-sentiment')
print(f"Result: { nlp(sentence) }")

Result: [{'label': '3 stars', 'score': 0.5285704731941223}]
